version: "3.9"
services:
  kamailio:
    privileged: true
    container_name: kamailio
    build: ./config_kamailio
    network_mode: "host"
    depends_on:
      - rtpengine
    volumes:
      - kamailio:/etc/kamailio
      - db:/var/lib/mysql
  rtpengine:
    privileged: true
    container_name: rtpengine
    build: ./rtpengine
    network_mode: "host"
    volumes:
      - rtpengine:/etc/rtpengine

volumes:
  kamailio:
  rtpengine:
  db: